// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.12.4
// source: api/proto/v1/rag/rag.proto

package rag

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IndexRequest contains the information for the documents to be indexed.
type IndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // The ID of the user performing the action.
	FolderId      string                 `protobuf:"bytes,2,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"` // The ID of the folder to index into.
	Paths         []string               `protobuf:"bytes,3,rep,name=paths,proto3" json:"paths,omitempty"`                       // A list of local file paths or remote URLs.
	Reindex       bool                   `protobuf:"varint,4,opt,name=reindex,proto3" json:"reindex,omitempty"`                  // If true, forces re-indexing.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexRequest) Reset() {
	*x = IndexRequest{}
	mi := &file_api_proto_v1_rag_rag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexRequest) ProtoMessage() {}

func (x *IndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_rag_rag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexRequest.ProtoReflect.Descriptor instead.
func (*IndexRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_rag_rag_proto_rawDescGZIP(), []int{0}
}

func (x *IndexRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IndexRequest) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *IndexRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *IndexRequest) GetReindex() bool {
	if x != nil {
		return x.Reindex
	}
	return false
}

// IndexResponse streams the progress of the indexing job.
type IndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Progress      int32                  `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexResponse) Reset() {
	*x = IndexResponse{}
	mi := &file_api_proto_v1_rag_rag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexResponse) ProtoMessage() {}

func (x *IndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_rag_rag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexResponse.ProtoReflect.Descriptor instead.
func (*IndexResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_rag_rag_proto_rawDescGZIP(), []int{1}
}

func (x *IndexResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *IndexResponse) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

// QueryRequest contains the user's query.
type QueryRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // The ID of the user performing the query.
	Query  string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`                 // The question to be answered.
	// A list of folder IDs to search within. If empty, searches all folders for the user.
	FolderIds     []string `protobuf:"bytes,3,rep,name=folder_ids,json=folderIds,proto3" json:"folder_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_api_proto_v1_rag_rag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_rag_rag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_rag_rag_proto_rawDescGZIP(), []int{2}
}

func (x *QueryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *QueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryRequest) GetFolderIds() []string {
	if x != nil {
		return x.FolderIds
	}
	return nil
}

// RetrievedDocument represents a chunk of a source document relevant to the query.
type RetrievedDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Score         float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrievedDocument) Reset() {
	*x = RetrievedDocument{}
	mi := &file_api_proto_v1_rag_rag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrievedDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrievedDocument) ProtoMessage() {}

func (x *RetrievedDocument) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_rag_rag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrievedDocument.ProtoReflect.Descriptor instead.
func (*RetrievedDocument) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_rag_rag_proto_rawDescGZIP(), []int{3}
}

func (x *RetrievedDocument) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RetrievedDocument) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *RetrievedDocument) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RetrievedDocument) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// QueryResponse contains the answer and the source documents.
type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	Sources       []*RetrievedDocument   `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_api_proto_v1_rag_rag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_rag_rag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_rag_rag_proto_rawDescGZIP(), []int{4}
}

func (x *QueryResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *QueryResponse) GetSources() []*RetrievedDocument {
	if x != nil {
		return x.Sources
	}
	return nil
}

// A folder object.
type Folder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Folder) Reset() {
	*x = Folder{}
	mi := &file_api_proto_v1_rag_rag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Folder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Folder) ProtoMessage() {}

func (x *Folder) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_rag_rag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Folder.ProtoReflect.Descriptor instead.
func (*Folder) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_rag_rag_proto_rawDescGZIP(), []int{5}
}

func (x *Folder) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Folder) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Folder) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// Request to create a new folder.
type CreateFolderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FolderName    string                 `protobuf:"bytes,2,opt,name=folder_name,json=folderName,proto3" json:"folder_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFolderRequest) Reset() {
	*x = CreateFolderRequest{}
	mi := &file_api_proto_v1_rag_rag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFolderRequest) ProtoMessage() {}

func (x *CreateFolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_rag_rag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFolderRequest.ProtoReflect.Descriptor instead.
func (*CreateFolderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_rag_rag_proto_rawDescGZIP(), []int{6}
}

func (x *CreateFolderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateFolderRequest) GetFolderName() string {
	if x != nil {
		return x.FolderName
	}
	return ""
}

// Response containing a single folder.
type FolderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folder        *Folder                `protobuf:"bytes,1,opt,name=folder,proto3" json:"folder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FolderResponse) Reset() {
	*x = FolderResponse{}
	mi := &file_api_proto_v1_rag_rag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FolderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FolderResponse) ProtoMessage() {}

func (x *FolderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_rag_rag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FolderResponse.ProtoReflect.Descriptor instead.
func (*FolderResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_rag_rag_proto_rawDescGZIP(), []int{7}
}

func (x *FolderResponse) GetFolder() *Folder {
	if x != nil {
		return x.Folder
	}
	return nil
}

// Request to list folders for a user.
type ListFoldersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFoldersRequest) Reset() {
	*x = ListFoldersRequest{}
	mi := &file_api_proto_v1_rag_rag_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFoldersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFoldersRequest) ProtoMessage() {}

func (x *ListFoldersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_rag_rag_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFoldersRequest.ProtoReflect.Descriptor instead.
func (*ListFoldersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_rag_rag_proto_rawDescGZIP(), []int{8}
}

func (x *ListFoldersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Response containing a list of folders.
type ListFoldersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folders       []*Folder              `protobuf:"bytes,1,rep,name=folders,proto3" json:"folders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFoldersResponse) Reset() {
	*x = ListFoldersResponse{}
	mi := &file_api_proto_v1_rag_rag_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFoldersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFoldersResponse) ProtoMessage() {}

func (x *ListFoldersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_rag_rag_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFoldersResponse.ProtoReflect.Descriptor instead.
func (*ListFoldersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_rag_rag_proto_rawDescGZIP(), []int{9}
}

func (x *ListFoldersResponse) GetFolders() []*Folder {
	if x != nil {
		return x.Folders
	}
	return nil
}

var File_api_proto_v1_rag_rag_proto protoreflect.FileDescriptor

const file_api_proto_v1_rag_rag_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/proto/v1/rag/rag.proto\x12\x06v1.rag\"t\n" +
	"\fIndexRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfolder_id\x18\x02 \x01(\tR\bfolderId\x12\x14\n" +
	"\x05paths\x18\x03 \x03(\tR\x05paths\x12\x18\n" +
	"\areindex\x18\x04 \x01(\bR\areindex\"E\n" +
	"\rIndexResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x05R\bprogress\"\\\n" +
	"\fQueryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x1d\n" +
	"\n" +
	"folder_ids\x18\x03 \x03(\tR\tfolderIds\"\xcf\x01\n" +
	"\x11RetrievedDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\x12C\n" +
	"\bmetadata\x18\x04 \x03(\v2'.v1.rag.RetrievedDocument.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\\\n" +
	"\rQueryResponse\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\x123\n" +
	"\asources\x18\x02 \x03(\v2\x19.v1.rag.RetrievedDocumentR\asources\"K\n" +
	"\x06Folder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\"O\n" +
	"\x13CreateFolderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vfolder_name\x18\x02 \x01(\tR\n" +
	"folderName\"8\n" +
	"\x0eFolderResponse\x12&\n" +
	"\x06folder\x18\x01 \x01(\v2\x0e.v1.rag.FolderR\x06folder\"-\n" +
	"\x12ListFoldersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"?\n" +
	"\x13ListFoldersResponse\x12(\n" +
	"\afolders\x18\x01 \x03(\v2\x0e.v1.rag.FolderR\afolders2\x87\x02\n" +
	"\n" +
	"RagService\x126\n" +
	"\x05Index\x12\x14.v1.rag.IndexRequest\x1a\x15.v1.rag.IndexResponse0\x01\x124\n" +
	"\x05Query\x12\x14.v1.rag.QueryRequest\x1a\x15.v1.rag.QueryResponse\x12C\n" +
	"\fCreateFolder\x12\x1b.v1.rag.CreateFolderRequest\x1a\x16.v1.rag.FolderResponse\x12F\n" +
	"\vListFolders\x12\x1a.v1.rag.ListFoldersRequest\x1a\x1b.v1.rag.ListFoldersResponseB\x1dZ\x1bJarvis_2.0/api/proto/v1/ragb\x06proto3"

var (
	file_api_proto_v1_rag_rag_proto_rawDescOnce sync.Once
	file_api_proto_v1_rag_rag_proto_rawDescData []byte
)

func file_api_proto_v1_rag_rag_proto_rawDescGZIP() []byte {
	file_api_proto_v1_rag_rag_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_rag_rag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_rag_rag_proto_rawDesc), len(file_api_proto_v1_rag_rag_proto_rawDesc)))
	})
	return file_api_proto_v1_rag_rag_proto_rawDescData
}

var file_api_proto_v1_rag_rag_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_v1_rag_rag_proto_goTypes = []any{
	(*IndexRequest)(nil),        // 0: v1.rag.IndexRequest
	(*IndexResponse)(nil),       // 1: v1.rag.IndexResponse
	(*QueryRequest)(nil),        // 2: v1.rag.QueryRequest
	(*RetrievedDocument)(nil),   // 3: v1.rag.RetrievedDocument
	(*QueryResponse)(nil),       // 4: v1.rag.QueryResponse
	(*Folder)(nil),              // 5: v1.rag.Folder
	(*CreateFolderRequest)(nil), // 6: v1.rag.CreateFolderRequest
	(*FolderResponse)(nil),      // 7: v1.rag.FolderResponse
	(*ListFoldersRequest)(nil),  // 8: v1.rag.ListFoldersRequest
	(*ListFoldersResponse)(nil), // 9: v1.rag.ListFoldersResponse
	nil,                         // 10: v1.rag.RetrievedDocument.MetadataEntry
}
var file_api_proto_v1_rag_rag_proto_depIdxs = []int32{
	10, // 0: v1.rag.RetrievedDocument.metadata:type_name -> v1.rag.RetrievedDocument.MetadataEntry
	3,  // 1: v1.rag.QueryResponse.sources:type_name -> v1.rag.RetrievedDocument
	5,  // 2: v1.rag.FolderResponse.folder:type_name -> v1.rag.Folder
	5,  // 3: v1.rag.ListFoldersResponse.folders:type_name -> v1.rag.Folder
	0,  // 4: v1.rag.RagService.Index:input_type -> v1.rag.IndexRequest
	2,  // 5: v1.rag.RagService.Query:input_type -> v1.rag.QueryRequest
	6,  // 6: v1.rag.RagService.CreateFolder:input_type -> v1.rag.CreateFolderRequest
	8,  // 7: v1.rag.RagService.ListFolders:input_type -> v1.rag.ListFoldersRequest
	1,  // 8: v1.rag.RagService.Index:output_type -> v1.rag.IndexResponse
	4,  // 9: v1.rag.RagService.Query:output_type -> v1.rag.QueryResponse
	7,  // 10: v1.rag.RagService.CreateFolder:output_type -> v1.rag.FolderResponse
	9,  // 11: v1.rag.RagService.ListFolders:output_type -> v1.rag.ListFoldersResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_v1_rag_rag_proto_init() }
func file_api_proto_v1_rag_rag_proto_init() {
	if File_api_proto_v1_rag_rag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_rag_rag_proto_rawDesc), len(file_api_proto_v1_rag_rag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_rag_rag_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_rag_rag_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_rag_rag_proto_msgTypes,
	}.Build()
	File_api_proto_v1_rag_rag_proto = out.File
	file_api_proto_v1_rag_rag_proto_goTypes = nil
	file_api_proto_v1_rag_rag_proto_depIdxs = nil
}
